name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🙏

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Drag and drop images here

  - type: dropdown
    id: device
    attributes:
      label: Device
      description: What device are you using?
      options:
        - iPhone
        - Android Phone
        - iPad
        - Android Tablet
        - Desktop Browser
        - Other
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser/App
      description: What browser or app are you using?
      placeholder: e.g., Safari, Chrome, Firefox, PWA

  - type: dropdown
    id: installed
    attributes:
      label: Installed as PWA?
      description: Is the app installed on your home screen?
      options:
        - "Yes"
        - "No"
        - "Not sure"

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.

